syntax = "proto3";

package lagrange;

import "google/protobuf/duration.proto";

message WorkerToGwResponse {
  UUID task_id = 1;
  bytes task = 2;
}

// A message sent by the prover at the beginning of connection to the GW
// Contains fields that were previously communicated via JWT claims.
message WorkerReady {
  // Version of the worker. Should follow SemVer format.
  string version = 1;
  // Class of the worker.
  string worker_class = 2;
}

message WorkerToGwRequest {
  oneof request {
    WorkerReady worker_ready = 1;
    WorkerDone worker_done = 2;
  }
}

service WorkersService {
  // A bidirectional streaming RPC between GW<->Worker
  rpc WorkerToGw(stream WorkerToGwRequest) returns (stream WorkerToGwResponse) {}
}

message WorkerDone {
  UUID task_id = 1;
  oneof reply {
    bytes task_output = 2;
    string worker_error = 3;
  }
}

message UUID {
  bytes id = 1;
}

message SubmitTaskRequest {
  bytes task_bytes = 1;

  // friendly name of a task for logging and tracing
  string user_task_id = 2;

  google.protobuf.Duration timeout = 3;

  bytes price_requested = 4;
  repeated string class = 5;

  // BE-encoded `U256`.
  bytes stake_requested = 6;

  // Priority of the task
  uint64 priority = 7;
}

message SubmitTaskResponse {
  UUID task_uuid = 2;
}

message AckedMessages {
  repeated UUID acked_messages = 1;
}

message SubscribeToMessages {
  repeated UUID subscribe_to_messages = 2;
}

message ProofChannelRequest {
  oneof request {
    AckedMessages acked_messages = 1;
    SubscribeToMessages subscribe_to_messages = 2;
  }
}

message ProofReady {
  UUID task_id = 1;
  bytes task_output = 2;
}

message ProofChannelResponse {
  oneof response {
    ProofReady proof = 1;
  }
}

service ClientsService {
  rpc SubmitTask(SubmitTaskRequest) returns (SubmitTaskResponse) {}
  rpc ProofChannel(stream ProofChannelRequest) returns (stream ProofChannelResponse) {}
}
