name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run buf-build checks
      uses: bufbuild/buf-action@v1
      with:
        # Only setup and custom commands to avoid logging into BSR
        # and publishing the schemas for the timebeing
        setup_only: true
        lint: true
        breaking: true
        format: true
