name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Protoc
      uses: arduino/setup-protoc@v3

    - uses: actions/checkout@v4

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: cargo build 
      run: cargo build --verbose 

    - name: cargo clippy
      run: cargo clippy -- -D warnings

    - name: cargo fmt
      run: cargo fmt --check
